# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/" # Location of your composer.json and composer.lock
    schedule:
      interval: "daily" # or "weekly", "monthly"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
