<?php

declare(strict_types=1);

namespace PhpIso\Test;

use PhpIso\Descriptor\Volume;
use PhpIso\IsoEntry;
use PhpIso\IsoFile;
use PHPUnit\Framework\TestCase;

/**
 * Images generated by xorriso / genisoimage (see fixtures/README.md): the expectations come from the tools, not
 * from the parser's own assumptions
 */
final class RealWorldFixturesTest extends TestCase
{
    private function image(string $name): IsoFile
    {
        return new IsoFile(dirname(__DIR__) . '/fixtures/' . $name);
    }

    /**
     * @return array<string, IsoEntry> by path
     */
    private function entries(IsoFile $isoFile, Volume $volume): array
    {
        $entries = [];
        foreach ($volume->walk($isoFile) as $entry) {
            $entries[$entry->path] = $entry;
        }

        return $entries;
    }

    private function volume(?Volume $volume): Volume
    {
        $this->assertInstanceOf(Volume::class, $volume);

        return $volume;
    }

    public function testRockRidgeSymlink(): void
    {
        $isoFile = $this->image('rockridge.iso');
        $entries = $this->entries($isoFile, $this->volume($isoFile->getPrimaryVolume()));

        $link = $entries['/link_to_hello'];
        $this->assertTrue($link->isSymlink());
        $this->assertSame('hello.txt', $link->getSymlinkTarget());
        $this->assertSame(0, $link->size);
        $this->assertSame(0120777, $link->mode);
    }

    public function testRockRidgeLongNameFromTheContinuationArea(): void
    {
        $isoFile = $this->image('rockridge.iso');
        $volume = $this->volume($isoFile->getPrimaryVolume());
        $name = str_repeat('long_name_', 21) . '.txt';

        $this->assertSame(214, strlen($name));
        $entries = $this->entries($isoFile, $volume);
        $this->assertArrayHasKey('/' . $name, $entries);
        $this->assertSame($name, $entries['/' . $name]->name);
        $this->assertSame(5, $entries['/' . $name]->size);
        $this->assertSame("long\n", $volume->readFile($isoFile, $entries['/' . $name]));
    }

    public function testRockRidgeDeepPathAndContent(): void
    {
        $isoFile = $this->image('rockridge.iso');
        $volume = $this->volume($isoFile->getPrimaryVolume());
        $entries = $this->entries($isoFile, $volume);

        $deep = $entries['/dir1/dir2/dir3/dir4/dir5/deep.txt'];
        $this->assertSame(5, $deep->size);
        $this->assertSame("deep\n", $volume->readFile($isoFile, $deep));
        $this->assertSame($deep->path, $volume->find($isoFile, '/DIR1/dir2/DIR3/dir4/dir5/DEEP.TXT')?->path);
        $this->assertTrue($entries['/dir1/dir2']->isDirectory);
    }

    public function testRockRidgeModeAndOwner(): void
    {
        $isoFile = $this->image('rockridge.iso');
        $entries = $this->entries($isoFile, $this->volume($isoFile->getPrimaryVolume()));

        $this->assertSame(0100644, $entries['/hello.txt']->mode);
        $this->assertSame(0040755, $entries['/dir1']->mode);
        $this->assertSame(0, $entries['/hello.txt']->uid);
        $this->assertSame(0, $entries['/hello.txt']->gid);
        $this->assertSame(17, $entries['/hello.txt']->size);
    }

    public function testRockRidgeCanBeIgnored(): void
    {
        $isoFile = $this->image('rockridge.iso');
        $volume = $this->volume($isoFile->getPrimaryVolume());

        $names = [];
        foreach ($volume->walk($isoFile, 64, null, false) as $entry) {
            $names[] = $entry->name;
        }

        $this->assertContains('HELLO.TXT', $names);
        $this->assertNotContains('hello.txt', $names);
    }

    public function testIso1999EnhancedVolume(): void
    {
        $isoFile = $this->image('iso1999.iso');
        $enhanced = $this->volume($isoFile->getEnhancedVolume());

        $this->assertSame('ISO1999', $enhanced->volumeId);
        $this->assertNull($isoFile->getSupplementaryVolume());

        $entries = $this->entries($isoFile, $enhanced);
        $this->assertSame(['/a_rather_long_file_name_for_level_four.txt', '/subdir', '/subdir/nested.dat'], array_keys($entries));
        $this->assertSame(32, $entries['/a_rather_long_file_name_for_level_four.txt']->size);
        $this->assertSame("nested\n", $enhanced->readFile($isoFile, $entries['/subdir/nested.dat']));
    }

    public function testIso1999PreferredVolumeNamesAreReadable(): void
    {
        $isoFile = $this->image('iso1999.iso');
        $preferred = $this->volume($isoFile->getPreferredVolume());

        $entries = $this->entries($isoFile, $preferred);
        $this->assertArrayHasKey('/a_rather_long_file_name_for_level_four.txt', $entries);
        $this->assertSame(32, strlen($preferred->readFile($isoFile, $entries['/a_rather_long_file_name_for_level_four.txt'])));
    }

    public function testJolietCjkVolumeId(): void
    {
        $isoFile = $this->image('joliet_cjk.iso');

        $this->assertSame('ボリューム中文', $this->volume($isoFile->getSupplementaryVolume())->volumeId);
        $this->assertSame(3, $this->volume($isoFile->getSupplementaryVolume())->jolietLevel);
        $this->assertSame('ボリューム中文', $this->volume($isoFile->getPreferredVolume())->volumeId);
    }

    public function testJolietCjkNames(): void
    {
        $isoFile = $this->image('joliet_cjk.iso');
        $volume = $this->volume($isoFile->getPreferredVolume());
        $entries = $this->entries($isoFile, $volume);

        $this->assertSame(['/ディレクトリ', '/中文文件.txt', '/日本語ファイル.txt', '/ディレクトリ/ネスト.txt'], array_keys($entries));
        $this->assertSame(8, $entries['/中文文件.txt']->size);
        $this->assertSame("chinese\n", $volume->readFile($isoFile, $entries['/中文文件.txt']));
        $this->assertSame("japanese\n", $volume->readFile($isoFile, $entries['/日本語ファイル.txt']));
        $this->assertSame("nested\n", $volume->readFile($isoFile, $entries['/ディレクトリ/ネスト.txt']));
        $this->assertTrue($entries['/ディレクトリ']->isDirectory);
    }

    public function testJolietCjkPrimaryTreeHasMangledNames(): void
    {
        $isoFile = $this->image('joliet_cjk.iso');
        $entries = $this->entries($isoFile, $this->volume($isoFile->getPrimaryVolume()));

        $this->assertArrayHasKey('/_____000.TXT', $entries);
        $this->assertCount(4, $entries);
    }

    public function testFilesWithoutAnExtensionKeepTheirNames(): void
    {
        $isoFile = $this->image('no_extension.iso');
        $volume = $this->volume($isoFile->getPrimaryVolume());
        $entries = $this->entries($isoFile, $volume);

        $this->assertSame(['/DATA.TXT', '/LICENSE', '/README'], array_keys($entries));
        $this->assertSame(7, $entries['/README']->size);
        $this->assertSame(13, $entries['/LICENSE']->size);
        $this->assertSame(5, $entries['/DATA.TXT']->size);
        $this->assertSame("readme\n", $volume->readFile($isoFile, $entries['/README']));
        $this->assertSame("license text\n", $volume->readFile($isoFile, $entries['/LICENSE']));
        $this->assertSame("data\n", $volume->readFile($isoFile, $entries['/DATA.TXT']));
    }

    public function testFilesWithoutAnExtensionAreFound(): void
    {
        $isoFile = $this->image('no_extension.iso');
        $volume = $this->volume($isoFile->getPrimaryVolume());

        $this->assertSame('/LICENSE', $volume->find($isoFile, 'license')?->path);
        $this->assertNotInstanceOf(IsoEntry::class, $volume->find($isoFile, 'LICENSE.'));
    }
}
